### ISSUE TITLE
Integrate specref into report

### ISSUE THREAD

**Issue by marcoscaceres** [w3c-webmob/coremob-report#1]
See: 
http://lists.w3.org/Archives/Public/public-web-mobile/2013Sep/0093.html

**Comment by jorabin** [comment]
Not sure that we'd want to do that, the document captures a point in time ...

**Comment by marcoscaceres** [comment]
The published document does that, but the editor's draft version of it can certainly make use of it.

**Comment by marcoscaceres** [comment]
I think I will just trash the status stuff instead. See https://github.com/w3c-webmob/coremob-report/issues/9.
