### ISSUE TITLE
Geolocation requirement already met

### ISSUE THREAD

**Issue by marcoscaceres** [w3c-webmob/coremob-report#27]
The doc says:

> It MUST be possible to obtain the device's current geographic coordinates provided the user consents to sharing those.

Geolocation is widely and implemented in an interoperable manner. This requirement should be either removed or updated to talk about geofencing.

**Comment by nrooney** [comment]
DKA: not sure about geofencing in particular, perhaps W3C geo group needs to work on more sophisticated use cases, and points of information.

**Comment by nrooney** [comment]
Note from W3C TPAC breakout session on geo: http://www.w3.org/wiki/TPAC2013/session-geolocation#Notes

**Comment by tobie** [comment]
The goal of Coremob 2012 was to paint a complete picture of the requirements, not only the missing ones.

**Comment by marcoscaceres** [comment]
Ok, will leave this in then.
